# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_to_seq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_to_seq.proto',
  package='',
  serialized_pb='\n\x13\x63lient_to_seq.proto\"@\n\x12\x43lientToSeqRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x02(\x0c\x12\x19\n\x11\x66lash_unit_number\x18\x02 \x02(\x05\"\x15\n\x13\x43lientToSeqResponse2H\n\x12\x43lientToSeqService\x12\x32\n\x05Write\x12\x13.ClientToSeqRequest\x1a\x14.ClientToSeqResponseB\x03\x90\x01\x01')




_CLIENTTOSEQREQUEST = _descriptor.Descriptor(
  name='ClientToSeqRequest',
  full_name='ClientToSeqRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_id', full_name='ClientToSeqRequest.data_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flash_unit_number', full_name='ClientToSeqRequest.flash_unit_number', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=87,
)


_CLIENTTOSEQRESPONSE = _descriptor.Descriptor(
  name='ClientToSeqResponse',
  full_name='ClientToSeqResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['ClientToSeqRequest'] = _CLIENTTOSEQREQUEST
DESCRIPTOR.message_types_by_name['ClientToSeqResponse'] = _CLIENTTOSEQRESPONSE

class ClientToSeqRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTTOSEQREQUEST

  # @@protoc_insertion_point(class_scope:ClientToSeqRequest)

class ClientToSeqResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTTOSEQRESPONSE

  # @@protoc_insertion_point(class_scope:ClientToSeqResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_CLIENTTOSEQSERVICE = _descriptor.ServiceDescriptor(
  name='ClientToSeqService',
  full_name='ClientToSeqService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=112,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='ClientToSeqService.Write',
    index=0,
    containing_service=None,
    input_type=_CLIENTTOSEQREQUEST,
    output_type=_CLIENTTOSEQRESPONSE,
    options=None,
  ),
])

class ClientToSeqService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _CLIENTTOSEQSERVICE
class ClientToSeqService_Stub(ClientToSeqService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _CLIENTTOSEQSERVICE

# @@protoc_insertion_point(module_scope)
