# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_token.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_token.proto',
  package='',
  serialized_pb='\n\x0fget_token.proto\"!\n\x0fGetTokenRequest\x12\x0e\n\x06number\x18\x01 \x02(\x05\"!\n\x10GetTokenResponse\x12\r\n\x05token\x18\x01 \x02(\x03\x32\x42\n\x0fGetTokenService\x12/\n\x08GetToken\x12\x10.GetTokenRequest\x1a\x11.GetTokenResponseB\x03\x90\x01\x01')




_GETTOKENREQUEST = _descriptor.Descriptor(
  name='GetTokenRequest',
  full_name='GetTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='GetTokenRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=52,
)


_GETTOKENRESPONSE = _descriptor.Descriptor(
  name='GetTokenResponse',
  full_name='GetTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='GetTokenResponse.token', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['GetTokenRequest'] = _GETTOKENREQUEST
DESCRIPTOR.message_types_by_name['GetTokenResponse'] = _GETTOKENRESPONSE

class GetTokenRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTOKENREQUEST

  # @@protoc_insertion_point(class_scope:GetTokenRequest)

class GetTokenResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTOKENRESPONSE

  # @@protoc_insertion_point(class_scope:GetTokenResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_GETTOKENSERVICE = _descriptor.ServiceDescriptor(
  name='GetTokenService',
  full_name='GetTokenService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=89,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetToken',
    full_name='GetTokenService.GetToken',
    index=0,
    containing_service=None,
    input_type=_GETTOKENREQUEST,
    output_type=_GETTOKENRESPONSE,
    options=None,
  ),
])

class GetTokenService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _GETTOKENSERVICE
class GetTokenService_Stub(GetTokenService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _GETTOKENSERVICE

# @@protoc_insertion_point(module_scope)
