# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequencer_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sequencer_service.proto',
  package='',
  serialized_pb='\n\x17sequencer_service.proto\"E\n\x17SequencerServiceRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x02(\x0c\x12\x19\n\x11\x66lash_unit_number\x18\x02 \x02(\x05\"\x1a\n\x18SequencerServiceResponse2W\n\x17SequencerServiceService\x12<\n\x05Write\x12\x18.SequencerServiceRequest\x1a\x19.SequencerServiceResponseB\x03\x90\x01\x01')




_SEQUENCERSERVICEREQUEST = _descriptor.Descriptor(
  name='SequencerServiceRequest',
  full_name='SequencerServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_id', full_name='SequencerServiceRequest.data_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flash_unit_number', full_name='SequencerServiceRequest.flash_unit_number', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=96,
)


_SEQUENCERSERVICERESPONSE = _descriptor.Descriptor(
  name='SequencerServiceResponse',
  full_name='SequencerServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['SequencerServiceRequest'] = _SEQUENCERSERVICEREQUEST
DESCRIPTOR.message_types_by_name['SequencerServiceResponse'] = _SEQUENCERSERVICERESPONSE

class SequencerServiceRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEQUENCERSERVICEREQUEST

  # @@protoc_insertion_point(class_scope:SequencerServiceRequest)

class SequencerServiceResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEQUENCERSERVICERESPONSE

  # @@protoc_insertion_point(class_scope:SequencerServiceResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_SEQUENCERSERVICESERVICE = _descriptor.ServiceDescriptor(
  name='SequencerServiceService',
  full_name='SequencerServiceService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=126,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='SequencerServiceService.Write',
    index=0,
    containing_service=None,
    input_type=_SEQUENCERSERVICEREQUEST,
    output_type=_SEQUENCERSERVICERESPONSE,
    options=None,
  ),
])

class SequencerServiceService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _SEQUENCERSERVICESERVICE
class SequencerServiceService_Stub(SequencerServiceService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _SEQUENCERSERVICESERVICE

# @@protoc_insertion_point(module_scope)
